- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/examples/CollectionApiExample.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/examples/SimpleExample.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/CollectionService.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Collection.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
> Removed field thngs from Collection.

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/mapping/ActionDeserializerImpl.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/CollectionService.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/action/Action.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/action/ActionType.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/action/CustomAction.java
> Added field collection in CustomAction.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Collection.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
> Added field type inside Collection.

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/mapping/ActionsDeserializer.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/mapping/EvrythngJacksonModuleImpl.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/mapping/TypeMapDeserializer.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/ActionService.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/action/Actions.java
> Custom action deserializer for single or array.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/action/Action.java
> Add createdByThng in the Action model

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Property.java
> Introduced property normalization method.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Product.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
> Expose activated timestamp to api

- evrythng-commons/pom.xml
- evrythng-java-wrapper/pom.xml
- pom.xml
- thng-resource-model/pom.xml
- Updated distributionManagement locations to point to maven central
- Added maven staging plugin
> Infraops 536

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/CollectionService.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Collection.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
> Added support for Collections of Collections.

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/ApplicationService.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/OAuthClient.java
> OAuth client API

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/TaskOnBatch.java
> ENGINE-1404: Introduced task result entity for tasks API on batches.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Project.java
> Project level short domains

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/li/UrlBinding.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/ShortIdTemplate.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Task.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/TaskOnBatch.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/ThngTemplate.java
refactored_branches
Should be "refactored_batches"
> Improved Batch and Task resources.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BaseAdiInputParameters.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BaseAdiOutputParameters.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/CsvAdiOutputParameters.java
> Added OutputParameters to Batch Populating Task

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/util/JSONUtils.java
- evrythng-java-wrapper/src/test/java/com/evrythng/java/wrapper/util/JSONUtilsTest.java
- thng-resource-model/pom.xml
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/core/DurableResourceModel.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/core/ResourceModel.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/core/ScopeResource.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Batch.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/FileBasedAdiInputParameters.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/FixedAmountAdiInputParameters.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/ListBasedAdiInputParameters.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Project.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Task.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
> Added validation for Batches and Tasks

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Batch.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
> Introduced total resource count by product in Batch resource model.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Account.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Operator.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/TwoFASecret.java
> [ ENGINE-1605 ] Adding implementation for 2FA

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/AuthService.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/access/ThngCredentials.java
> Wrapper for GET auth/evrythng/thngs/id.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Thng.java
> Added field createdByTask to Thng resource model.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/jobs/JobLogEntry.java
> Renamed JobLogEntry.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Place.java
Augment 'Place' to support, and be filtered by, identifiers.
> Augment 'Place' to support, and be filtered by, identifiers.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Collection.java
> Add Identifiers to Collections

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/AddressInfo.java
> Fix GeoIP lookup for KR, IR, MD

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
> Fix the progress contributions reporting for Batch populating tasks

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/core/ResourceModel.java
> Case-sensitive CustomFields.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Task.java
> Added equals and hashcode for NotificationPolicy.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/AbstractUser.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Operator.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/security/passwords/WithPassword.java
> Added withPassword interface.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/BatchPopulatingTask.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/jobs/JobLogEntry.java
> Introduced fields for better logs in errors for tasks.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/exception/ErrorMessage.java
> Added utility method to ErrorMessage.

- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/core/Identifiable.java
- thng-resource-model/src/main/java/com/evrythng/thng/resource/model/store/Task.java
> Tasks are now Identifiable.

- README.md
As per a test resulting from a UserVoice query, document the single step required to enable Android SDK compatibility. Dom recommended that we document this on the Developer Hub and this SDK README.md file. 
Asana task: https://app.asana.com/0/102088471634779/210753951077453
> Add note about Android support

- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/ActionService.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/CollectionService.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/ProductService.java
- evrythng-java-wrapper/src/main/java/com/evrythng/java/wrapper/service/ThngService.java
Added iterator support for:
`/thngs/../actions`
`/products/../actions`
`/collections/../actions`
> JAVA-183: Iterator support for action alias endpoints.
